name: XCode Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [M1, monterey]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest-stable
    - name: Unit Specs on macOS
      uses: sersoft-gmbh/xcodebuild-action@v1.4
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Legible_Tests_macOS
        result-bundle-path: test-results/unit-specs
        build-settings: -test-timeouts-enabled YES
    - name: Unit Specs on iOS
      uses: sersoft-gmbh/xcodebuild-action@v1.4
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Legible_Tests_iOS
        result-bundle-path: test-results/unit-specs
        destination: platform=iOS Simulator,name=iPad (9th generation)
        build-settings: -test-timeouts-enabled YES
    - name: Performance Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.4
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Legible_Tests_macOS
        test-plan: Performance
        result-bundle-path: test-results/performance-tests
        build-settings: -test-timeouts-enabled YES
    - name: Save Performance baselines
      run: cp -R Example/Legible.xcodeproj/xcshareddata/xcbaselines ./test-results/
    - name: Save crash reports created since test-results
      if: failure()
      run: find ~/Library/Logs/DiagnosticReports/*.crash -newerBB ./test-results
        -exec cp {} ./test-results \; || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-results
        path: test-results
